var GAME_LEVELS = [
  
    ["  x                                                                          x  ", 
   "  x                                                                          x  ",
   "  x                                                                    o     x  ",
   "  x                                                                   xx     x  ",
   "  x                                                                          x  ",
   "  x                 x      o       o      o        o        o        =      =x  ",
   "  x                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            x  ",
   "  x           o                                                             ox  ",
   "  xo         xx                                                             xx  ",
   "  xx                                                                         x  ",
   "  x                                                                    xx    x  ",
   "  x    xx                                                        o           x  ",
   "  x                                                             xx           x  ",
   "  x                                                                          x  ",
   "  xx                                                   xx                    x  ",
   "  x                                                                          x  ",
   "  x     o                                                                    x  ",
   "  x    xx             o            o                    o                    x  ",
   "  x                  xxx    x     xxx    x   xx       xxx                    x  ",
   "  xx                 xxx    x     xxx                                        x  ",
   "  x                  xxx    x     xxx                                        x  ",
   "  x                  xxx!!!!x!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x  @      s        xxx!!!!x!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ", 
   "                                                                                                                  ",
   "   @    x!x                                                                                              xxxxxxxxx",
   "  xxx    |                                                                                                x       ",
   "  x                                                                                                       x =    o",
   "  x                                                                                                       x     xx",
   "  x      o                                                                                                        ",
   "  xo     x                                                                                                        ",
   "  xxx    |                                                                                                      xx",
   "  x                                                                                                               ",
   "  x                                                                                                      o    xx  ",
   "  x                                                                                                     xx        ",
   "  x      o                                                                                                        ",
   "  xo     x                                                                         xx            xx               ",
   "  xxx                                                                      o         x          x                 ",
   "  x                                                                       xxx          x       x                  ",
   "  x                                                              x     x                x ooo x                   ",
   "  x                     o                                                                 xxx                     ",
   "  xo           s       xx       x=              =x    xx        xx                                                ",
   "  xxx    |    xxx      xx               o              xx                                                         ",
   "  x      x             xx              xxx             xx                                                         ",
   "  x                    xx                              xx                                                         ",
   "  x!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
 
   
   
  ["           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "   @       x  x!!x                                                                                            ",
   "xxxxx      x  x!!x               o        o          o             o              o          o                ",
   "x          x   ||         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             ",
   "x          x             x                                                                      x             ",
   "x          x            x                                                                       x          xxx",
   "x          x           x                                                                        x         =   ",
   "x          x          x                                                                         x    =        ",
   "x         ox   o                                                                                x             ",
   "x         xx   xxx                                                                              x    o        ",
   "x  x!!!!x  x                                                                                    x             ",
   "x  xxxxxx  x       x                                                                            x     o       ",
   "x         |x            o                                                                       x             ",
   "xo         x           xxx                                                                      x      o      ",
   "xx      o  x                  x      o                                                          x             ",
   "x       o  x                  x     xxx                                                         x             ",
   "x       o  x                                                                                    x     o       ",
   "x  x    o  x                              xx                                                    x             ",
   "x       o  x                                                                                    x             ",
   "x       o  x                                                          s                         x     o       ",
   "x      o   x           |         xxxxxxxxxxxx                         x                         x             ",
   "x   x o    x             xx      x          x                        xxx                        x             ",
   "x     o            xxx   xx    xxx          x                       xxxxx                       x             ",
   "x                  x     xx                 x                      xxxxxxx                      x             ",
   "x!!!!!xxxxxx       x o   xx       o    =    x                     xxxxxxxxx                     x o           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             ",
   "x                                                                                               x  x          ",
   "x                                                                                               x     x!!!!!!!!",
   "x                                                                                               xo    xxxxxxxx",
   "x                                                                                               x             ",
   "x                                                                                               x             ",
   "x                                                                                               x             ",
   "x                                                                                               x             ",
   "x                                                                                               x             ",
   "x                                                                                               x             ",
   "x                                                                                               x             ",
   "x                                                                                               x             ",
   "x                                                                                               x             ",
   "x                                                                                               x             ",
   "x                                                                                               xo            ",
   "x                                                                                               x             ",
   "x                                                                                               x            o",
   "                                                                                                xx    x      x",
   "                                                                                                x!!!!!!!!!!!!!",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
